### ISSUE TITLE
can't read property 'showFullscreen' of undefined

### ISSUE THREAD

**Issue by patricktresp** [ShariqMush/react-native-fullscreenvideo-player#1]
Hi i am getting an error using this repo when using the fullscreen button on Android only.

Pause and mute Buttons work properly, but the fullscreen button fires an exception.

I am using 
react-native-cli: 2.0.1
react-native: 0.48.3

is there a hint you can give me? The error seems to get fired because of this line

`NativeModules.BridgeModule.showFullscreen(uri);`  at index.js

How do i get BridgeModule available in NativeModules

![09 10 2017 15 18 53player](https://user-images.githubusercontent.com/1619156/31340129-81e11f50-ad05-11e7-8be2-f5035758dbc6.png)

Thanks!

Patrick

**Comment by patricktresp** [comment]
ok i found out it had to to with BridgePackage.java. which was not in correct folder.
Not the app Crashes everytime the fullscreen button is hit.
When trying to compile this causes a build error 
`@Override
    public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    } `

with this

android/app/src/main/java/BridgePackage.java:17: error: method does not override or implement a method from a supertype
    @Override

so i uncommented @Override which offers compiling, but forces the app to crash without any log. ( fatal crash )

The example causes the same error ...

**Comment by patricktresp** [comment]
i am closing this issue due to title - opening a new one…

**Comment by MP-OT** [comment]
Hello,

I am having the same issue. Any update about it?

Thanks!
