### ISSUE TITLE
Several Android errors

### ISSUE THREAD

**Issue by XaviSmith** [ShariqMush/react-native-fullscreenvideo-player#4]
Hi, I'm running react-native 0.50.4, followed the instructions and am getting the following errors

/android/app/src/main/res/layout/player_fullscreen.xml:42: AAPT: Error parsing XML: not well-formed (invalid token)

Followed by a stream of errors that's been accumulating for the past 5 minutes with errors such as

/android/app/src/main/java/com/cspatientapp/BridgeModule.java:7: error: class, interface, or enum expected
<!DOCTYPE html>
^
.../android/app/src/main/java/com/cspatientapp/BridgeModule.java:30: error: illegal character: '\u00b7'
  <title>react-native-fullscreenvideo-player/BridgeModule.java at master · ShariqMush/react-native-fullscreenvideo-player</title>
                                                                         ^
/android/app/src/main/java/com/cspatientapp/BridgeModule.java:58: error: <identifier> expected
  <meta class="js-ga-set" name="dimension1" content="Logged In">
             ^
/android/app/src/main/java/com/cspatientapp/BridgeModule.java:58: error: illegal start of type
  <meta class="js-ga-set" name="dimension1" content="Logged In">
              ^
/android/app/src/main/java/com/cspatientapp/BridgeModule.java:58: error: ';' expected
  <meta class="js-ga-set" name="dimension1" content="Logged In">
                                           ^
/android/app/src/main/java/com/cspatientapp/BridgeModule.java:58: error: <identifier> expected
  <meta class="js-ga-set" name="dimension1" content="Logged In">
                                                   ^
/android/app/src/main/java/com/cspatientapp/BridgeModule.java:63: error: > expected
      <meta name="hostname" content="github.com">
            ^
/Users/medtrakmb2/Documents/PatientApp/android/app/src/main/java/com/cspatientapp/BridgeModule.java:63: error: ';' expected
      <meta name="hostname" content="github.com">
                           ^
/android/app/src/main/java/com/cspatientapp/BridgeModule.java:63: error: <identifier> expected
      <meta name="hostname" content="github.com">
                                   ^
/android/app/src/main/java/com/cspatientapp/BridgeModule.java:64: error: > expected
  <meta name="user-login" content="XaviSmith">
        ^
/android/app/src/main/java/com/cspatientapp/BridgeModule.java:64: error: ';' expected
  <meta name="user-login" content="XaviSmith">
                         ^
/android/app/src/main/java/com/cspatientapp/BridgeModule.java:64: error: <identifier> expected
  <meta name="user-login" content="XaviSmith">
                                 ^
/android/app/src/main/java/com/cspatientapp/BridgeModule.java:66: error: > expected
      <meta name="expected-hostname" content="github.com">
            ^
/android/app/src/main/java/com/cspatientapp/BridgeModule.java:66: error: ';' expected
      <meta name="expected-hostname" content="github.com">
                                    ^
/android/app/src/main/java/com/cspatientapp/BridgeModule.java:66: error: <identifier> expected
      <meta name="expected-hostname" content="github.com">
                                            ^
/android/app/src/main/java/com/cspatientapp/BridgeModule.java:67: error: > expected
    <meta name="js-proxy-site-detection-payload" content="YmUxMmRhNzdlYzJkZmY0NTIxNGVkNzljMzg3ZDkxMjJhYmY2Zjg1OGQ1ZDVjZmU2NWE3ZjU3ODhkYmRmNTFjM3x7InJlbW90ZV9hZGRyZXNzIjoiNjkuMjQyLjYyLjE5MiIsInJlcXVlc3RfaWQiOiIxRTRGOjUyQUI6NDBBN0I6NzgxQ0U6NUEyODBGRUQiLCJ0aW1lc3RhbXAiOjE1MTI1NzQ5NTcsImhvc3QiOiJnaXRodWIuY29tIn0=">
          ^
android/app/src/main/java/com/cspatientapp/BridgeModule.java:67: error: ';' expected
    <meta name="js-proxy-site-detection-payload" content="YmUxMmRhNzdlYzJkZmY0NTIxNGVkNzljMzg3ZDkxMjJhYmY2Zjg1OGQ1ZDVjZmU2NWE3ZjU3ODhkYmRmNTFjM3x7InJlbW90ZV9hZGRyZXNzIjoiNjkuMjQyLjYyLjE5MiIsInJlcXVlc3RfaWQiOiIxRTRGOjUyQUI6NDBBN0I6NzgxQ0U6NUEyODBGRUQiLCJ0aW1lc3RhbXAiOjE1MTI1NzQ5NTcsImhvc3QiOiJnaXRodWIuY29tIn0=">
                                                ^

and so on

**Comment by ShariqMush** [comment]
@XaviSmith Seems like you made an error while bridging the android classes and files. I have not tested the project with the latest rn version but can you try it with rn 46 to check if it is a version incompatibility issue?

**Comment by XaviSmith** [comment]
Hey, unfortunately for this project i have to use RN 0.50.4 and it would take a very long time to downgrade rn and upgrade it again due to how many different modules we depend on
