### ISSUE TITLE
Android Full Screen Mode Video Playing from Starting

### ISSUE THREAD

**Issue by dip77** [ShariqMush/react-native-fullscreenvideo-player#7]
In Android Full Screen Mode ,Video playing from Starting rather than continuing from where I pressed Full Screen
For the Android Full Screen I Have used,
NativeModules.BridgeModule.showFullscreen(uri);

RN 0.43

Would really Appreciate if someone can solve this issue, had spent too much time solving this and
Product need to release ASAP.

**Comment by ShariqMush** [comment]
@dip77 You need to pass a callback from the react code and seek the video player to that time.

**Comment by dip77** [comment]
can you give the code snippet?

**Comment by dip77** [comment]
also when i open the full screen it shows buffering which shouldn't be done, can you provide some code for that.

**Comment by ShariqMush** [comment]
@dip77 It has to buffer because when you are entering fullscreen, it loads the video into the native player which has to buffer so I cannot provide any solution for that at the moment but for the callbacks, you can check the main videoplayer library and I haven't worked on the callbacks yet but I will in a future update soon.

**Comment by dip77** [comment]
i solved this issue by writing native code,

- **VideoPlayer**

 (in file index.js)**

onToggleFullScreen() {
    if(Platform.OS === "android")
    {
      var uri = this.props.video.uri;
      **NativeModules.BridgeModule.showFullscreen(uri,currentTime*1000)**;//passing MS as duration
      //currentTime is stored in state and changes whenever onProgress gets called
 }
    else
    {
      this.player.presentFullscreenPlayer();
    }

- **BrdigeModule.java**

 @ReactMethod
    public void showFullscreen(String videoUri,int duraitonToSeek) {
        **duration=duraitonToSeek; // duration is static variable**
        Context context = getReactApplicationContext();
        Intent intent = new Intent(context, VideoActivity.class); 
        intent.putExtra("VIDEO_URL",videoUri);
        getCurrentActivity().startActivity(intent);
    }

- **VideActivity.java**

myVideoView.setOnPreparedListener(new MediaPlayer.OnPreparedListener() {
                public void onPrepared(MediaPlayer mp) {
                    progressDialog.dismiss();
                    **myVideoView.seekTo(BridgeModule.duration);**
                    myVideoView.start();
                }
            });

**Comment by ShariqMush** [comment]
@dip77 Thanks alot for the solution dude
